### PR TITLE
add_dependencies

### PR DESCRIPTION
**Pull request by afsaneh-rezaeinejad-deriv**
add pixelmatch and pngjs as dependancies

### CODE REVIEW

**Review by bilalmajid-deriv — COMMENTED** [review]
@afsaneh-rezaeinejad-deriv 
could you rather add it as a dev dependency similar to the other node modules to maintain uniformity

**Review by bilalmajid-deriv — APPROVED** [review]
LGTM

**Review by markodonnell-deriv — APPROVED** [review]
Looks good

**Review by meeyun-deriv — APPROVED** [review]
LGTM

**Pull request merged**
