### PR TITLE
Added test for QATEST-20010

### PR DESCRIPTION
**Pull request by bilalmajid-deriv**
Added test for verifying Cashier withdrawal in multiple languages. Added fixture file for this test to save all content. Updated the ratelimit() command to be retry able and have custom parameters as well.

Just to add for the rate limit we will have to stop test execution for 15 seconds so that the run is not flaky 
I tried with 10 sec wait but the results were more flaky

### CODE REVIEW

**Review by meeyun-deriv — APPROVED** [review]
LGTM

**Review by abuzar-deriv — APPROVED** [review]
Looks good.

**Review by markodonnell-deriv — APPROVED** [review]
Looks good

**Comment by bilalmajid-deriv** [comment]
@meeyun-deriv have added the withdrawal link verification as well added a temporary command in the test file which will be removed once PR https://github.com/deriv-com/e2e-deriv-app/pull/132  is merged which has the required updates for email verification custom command, thanks.

**Comment by bilalmajid-deriv** [comment]
Closing this PR because this is very Old and a lot of conflicts.

**Pull request closed without merging**
