### PR TITLE
Ivo/IDV underage

### PR DESCRIPTION
**Pull request by ivo-deriv**
Adds test spec for IDV underage test spec

### CODE REVIEW

**Comment by bilalmajid-deriv** [comment]
@ivo-deriv seems like prettier is not running for you can you please run `npm i` and then change something in your test file and commit again to make prettier work for you. Thanks 🙏

**Review by bilalmajid-deriv — APPROVED** [review]

**Review by meeyun-deriv — CHANGES_REQUESTED** [review]
Please include mobile view for the test

**Review by meeyun-deriv — CHANGES_REQUESTED** [review]
Please move the test to `smoke` folder

**Review by meeyun-deriv — APPROVED** [review]
LGTM

**Pull request merged**
