### PR TITLE
[New Spec - Add additional Payment Methods] [Enhancements - Support added for all types of payment methods] [Minor changes in respect to enhancements]

### PR DESCRIPTION
**Pull request by usman-deriv**
### - Enhancements
1. Now supporting the adding of **ALL** types of Payment Methods (bank Transfers, E-wallets, Others) - Formerly was only for Bank transfers. 
2. Minor changes are done in support of the enhancement for point (1). 
3. Refactoring for addFirst, deletePayment, editPayment specs to remove unused variables. 

[ClickUp Card for Add Multi Payment Methods](https://app.clickup.com/t/20696747/P2PS-2533)

Please find the attached screenshot for cypress run: 
Cypress Run for Spec Files

### CODE REVIEW

**Review by bilalmajid-deriv — CHANGES_REQUESTED** [review]
please keep the variable for PaymentName and pass paymentName through it only.
it would be easy to maintain

**Review by bilalmajid-deriv — APPROVED** [review]
LGTM

**Review by markodonnell-deriv — APPROVED** [review]
Looks good

**Review by abuzar-deriv — APPROVED** [review]
Looks good.

**Review by meeyun-deriv — APPROVED** [review]
LGTM

**Pull request merged**
