### PR TITLE
Move back IDV tests into smoke folder

### PR DESCRIPTION
**Pull request by bertrand-deriv**
### Move back IDV tests into smoke folder

 - Moving the IDV tests into smoke folder as they are stable
 
 
Screenshot 2024-07-24 at 10 39 57

### CODE REVIEW

**Review by bilalmajid-deriv — APPROVED** [review]
LGTM

**Review by rajendra-deriv — APPROVED** [review]
LGTM

**Review by abuzar-deriv — CHANGES_REQUESTED** [review]
First test failed for me on re-run. Does these work for you on re-run?
image

**Comment by bertrand-deriv** [comment]
Hi @abuzar-deriv 
I'm not sure about what happened
But I have been running all the test suite multiple times and they were passing
Can you tell me which qabox did you use?
Can you also try to trigger again

**Review by abuzar-deriv — APPROVED** [review]

**Review by bilalmajid-deriv — APPROVED** [review]

**Pull request merged**
